#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $BET_MAKER_DB_USER WITH PASSWORD '$BET_MAKER_DB_PASSWORD';
    ALTER DATABASE $BET_MAKER_POSTGRES_DB OWNER TO $BET_MAKER_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $BET_MAKER_POSTGRES_DB TO $BET_MAKER_DB_USER;
EOSQL