FROM python:3.11.6-slim

WORKDIR /bet_maker

RUN apt-get update && apt-get install -y netcat-openbsd

COPY bet_maker/requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY bet_maker/ .
COPY .env .

ENV PYTHONPATH="/:/bet_maker"

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000", "--lifespan", "on"]
