FROM python:3.11.6-slim

WORKDIR /line_provider

COPY line_provider/requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY line_provider/ .

ENV PYTHONPATH="/:/line_provider"

CMD ["uvicorn", "app.main:app_line_provider", "--host", "0.0.0.0", "--port", "3001", "--lifespan", "on"]
